// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/user_profile.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserProfile struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               []byte                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Location             string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	BirthDay             *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=birth_day,json=birthDay,proto3" json:"birth_day,omitempty"`
	Email                string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Picture              string                 `protobuf:"bytes,7,opt,name=picture,proto3" json:"picture,omitempty"`
	CountryCode          string                 `protobuf:"bytes,8,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	PhoneNumber          string                 `protobuf:"bytes,9,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Bio                  string                 `protobuf:"bytes,10,opt,name=bio,proto3" json:"bio,omitempty"`
	IsFinishedOnboarding bool                   `protobuf:"varint,11,opt,name=is_finished_onboarding,json=isFinishedOnboarding,proto3" json:"is_finished_onboarding,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_proto_user_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_proto_user_profile_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfile) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UserProfile) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *UserProfile) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UserProfile) GetBirthDay() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDay
	}
	return nil
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserProfile) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *UserProfile) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *UserProfile) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserProfile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserProfile) GetIsFinishedOnboarding() bool {
	if x != nil {
		return x.IsFinishedOnboarding
	}
	return false
}

func (x *UserProfile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserProfile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type AuthorizeUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeUserRequest) Reset() {
	*x = AuthorizeUserRequest{}
	mi := &file_proto_user_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeUserRequest) ProtoMessage() {}

func (x *AuthorizeUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeUserRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_profile_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizeUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AuthorizeUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeUserResponse) Reset() {
	*x = AuthorizeUserResponse{}
	mi := &file_proto_user_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeUserResponse) ProtoMessage() {}

func (x *AuthorizeUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeUserResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_profile_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizeUserResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *AuthorizeUserResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_user_profile_proto protoreflect.FileDescriptor

const file_proto_user_profile_proto_rawDesc = "" +
	"\n" +
	"\x18proto/user_profile.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x03\n" +
	"\vUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\fR\x06userId\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x127\n" +
	"\tbirth_day\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bbirthDay\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x18\n" +
	"\apicture\x18\a \x01(\tR\apicture\x12!\n" +
	"\fcountry_code\x18\b \x01(\tR\vcountryCode\x12!\n" +
	"\fphone_number\x18\t \x01(\tR\vphoneNumber\x12\x10\n" +
	"\x03bio\x18\n" +
	" \x01(\tR\x03bio\x124\n" +
	"\x16is_finished_onboarding\x18\v \x01(\bR\x14isFinishedOnboarding\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"/\n" +
	"\x14AuthorizeUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"Z\n" +
	"\x15AuthorizeUserResponse\x12+\n" +
	"\aprofile\x18\x01 \x01(\v2\x11.user.UserProfileR\aprofile\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2W\n" +
	"\vUserService\x12H\n" +
	"\rAuthorizeUser\x12\x1a.user.AuthorizeUserRequest\x1a\x1b.user.AuthorizeUserResponseB#Z!github.com/sporthub11/grpc_lib/pbb\x06proto3"

var (
	file_proto_user_profile_proto_rawDescOnce sync.Once
	file_proto_user_profile_proto_rawDescData []byte
)

func file_proto_user_profile_proto_rawDescGZIP() []byte {
	file_proto_user_profile_proto_rawDescOnce.Do(func() {
		file_proto_user_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_profile_proto_rawDesc), len(file_proto_user_profile_proto_rawDesc)))
	})
	return file_proto_user_profile_proto_rawDescData
}

var file_proto_user_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_user_profile_proto_goTypes = []any{
	(*UserProfile)(nil),           // 0: user.UserProfile
	(*AuthorizeUserRequest)(nil),  // 1: user.AuthorizeUserRequest
	(*AuthorizeUserResponse)(nil), // 2: user.AuthorizeUserResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_proto_user_profile_proto_depIdxs = []int32{
	3, // 0: user.UserProfile.birth_day:type_name -> google.protobuf.Timestamp
	3, // 1: user.UserProfile.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: user.UserProfile.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: user.AuthorizeUserResponse.profile:type_name -> user.UserProfile
	1, // 4: user.UserService.AuthorizeUser:input_type -> user.AuthorizeUserRequest
	2, // 5: user.UserService.AuthorizeUser:output_type -> user.AuthorizeUserResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_user_profile_proto_init() }
func file_proto_user_profile_proto_init() {
	if File_proto_user_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_profile_proto_rawDesc), len(file_proto_user_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_profile_proto_goTypes,
		DependencyIndexes: file_proto_user_profile_proto_depIdxs,
		MessageInfos:      file_proto_user_profile_proto_msgTypes,
	}.Build()
	File_proto_user_profile_proto = out.File
	file_proto_user_profile_proto_goTypes = nil
	file_proto_user_profile_proto_depIdxs = nil
}
